helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:d5427fa1524e3e6f87c59e5cbc59e782036a2b5274e4f96cfb581d844aa2b6dc
    forcestring: true
