helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:6b71b69a0c71793e8a68d881145fd973e6e796ad7d82d482ecefce5ed3e00ae4
    forcestring: true
