helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:bdbbdef700868c8853bb3d55cfae2f2ac92565a4fbb40b683453e80e1abf6d92
    forcestring: true
