helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:57d2e3f4a8096cc715a983659f0a1187ef6a8d846c27fa9e41a51a9db2a820a4
    forcestring: true
