helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:a9d9fe330574d16be5a68175f2572615f9e55385695ab40652cc388076a07643
    forcestring: true
