helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:ffa9d723af7042840cad3404571a7ed8d53b86c256ca68b232e13b9f951eed8c
    forcestring: true
