helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:7e4abebd08cde4d424136f728c3e3614096b6f87c8e8d4766ea4ea2bf348be23
    forcestring: true
