helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:f333e559ec49c5745c4d817caa3862a1b52f7bd9ad7823cf1ec2236041f5e7c5
    forcestring: true
