helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:02c014712be5bf143bb58dbe9c468823af832d51b3948be2bc70c1ecfb0f1fc6
    forcestring: true
