helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:62df5d7fc3efaadb42df9a69dcd2afcd2e40f384087b7b9d65dfef5dfd7a6426
    forcestring: true
