helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:27acafe12f6f49d63e7e81ec059df16d5473e1331d23015e67195c8ce8957a38
    forcestring: true
