helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:e3b50147a9d1ce1725fb5572bd5ecdd474b8cda65ab59c13cf78370b4eb1f0fe
    forcestring: true
