helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:4e3c48268ebd40266b2906c8e0e383c63546b4363aeaa0d80e4be41cbe3a3f9d
    forcestring: true
