helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:ed70375179bf621076ee9c53d98bafd40c37c9971f308676d29123ed06be2bed
    forcestring: true
