helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:351e3625a56026c6b1be369815758ce49c420cdb9409e1d668fada1448feba49
    forcestring: true
