helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:43c69a7e573ddedf4bf2548c2cee1fca09e74a9667d04f2d0520a1209be78e85
    forcestring: true
