helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:9246a8bc914a69c20ce7fec17fade9f1047774a303f700e678b3725fbb690849
    forcestring: true
