helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:51beba0e5104a21b3955cec166519293a12b4f8b60275177b2813fca1d08e437
    forcestring: true
