helm:
  parameters:
  - name: image.repository
    value: ghcr.io/wez/govee2mqtt
    forcestring: true
  - name: image.tag
    value: latest@sha256:fed1ffc253325ef27534e8df49d52404b24a8c13c2fe362a42fd542f4c6bcee4
    forcestring: true
